### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by kenchasonakai** [monaka0309/nanikiru#118]
MVPレビューおめでとうございます！
このissueのコメントに本リリース予定日の回答をお願いいたします
以下にレビュー内容を記載します

## サービス概要について
> みなさんは麻雀をやっていて何を切っていいか分からない時はありませんか？[なにきる]ではその悩みを解決します。

リアルタイムで投稿するのは時間制限があるアプリだとなかなか厳しいものがあるんじゃないかなという印象なので、リアルタイムで何を切ればいいのかを相談できるようにするか、サービス説明を変えることを検討してもよいかもと思いました

## コード周りについて
Sorcery入ってるのに自分でcurrent_userやrequire_loginを定義してしまっているのでSorceryについて再度調べてみてください
データの編集等の操作時にcurrent_user起点になっていないので他の人のデータを操作されてしまうようになっている箇所が何箇所かありセキュリティ的に問題があるので見直してください
JavaScriptでは基本的にvarではなくletかconstを使うとモダンです
`具体的な意見と伝えることもできます。` → `具体的な意見を伝えることもできます。`ですかね？
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/e81fcaa8e333ff9f3bd5ec4bd3ff43cf.jpg)](https://startup-technology.gyazo.com/e81fcaa8e333ff9f3bd5ec4bd3ff43cf)

## 追加の技術案について
その後の機能で追加する予定のもの以外にGitHubActionsを使った自動デプロイ・自動テスト機能やDockerを使った開発環境の構築などを行うとより技術でアピール出来るポイントを作れそうです

**Comment by monaka0309** [comment]
ご指摘ありがとうございました。
本リリース予定日、4/30を目指して進めていきたいと思います。
